version: '2'
services:
  scormengine:
    image: 'registry.code.go1.com.au/microservices/scormengine:master'
    mem_reservation: '128M'
    ports:
      - '9999:80'
    extra_hosts:
      - host:${MONOLITH_HOST_IP}
    environment:
      - RDS_HOST=host
      - RDS_USER=root
      - RDS_PASS=root
      - RDS_NAME=scorm_dev
      - RDS_PORT=3306
      - ENVIRONMENT=dev
    volumes:
      - './.data/scormengine:/Library'
      - './.data/scormengine/WebServer/Documents:/usr/local/tomcat/webapps/Scorm'
