version: '2'
services:
    ui_live:
        build: ./.data/resources/docker/ui
        volumes:
            - './web/ui:/apiomui-live/'
        working_dir: /apiomui-live
        command: ["grunt", "serve"]
        ports:
            - '9090:9090'
            - '35729:35729'
