version: '2'
services:
    web:
        links:
            - scormengine
        environment:
            # Scorm's environments
            - SCORMENGINE_ENDPOINT=http://scormengine/ScormEngineInterface/api/v1
            - SCORMENGINE_LAUNCH=http://${ENV_HOSTNAME}:9999
    scormengine:
        build: ./.data/resources/docker/scormengine
        links:
            - mysql
        mem_reservation: '128M'
        ports:
            - '9999:80'
        extra_hosts:
            - host:${MONOLITH_HOST_IP}
        environment:
            - RDS_HOST=mysql
            - RDS_USER=root
            - RDS_PASS=root
            - RDS_NAME=scorm_dev
            - RDS_PORT=3306
            - ENVIRONMENT=dev
        volumes:
            - './.data/scormengine:/Library'
            - './.data/scormengine/WebServer/Documents:/usr/local/tomcat/webapps/Scorm'
