version: '2'
services:
    mysql:
        image: 'mysql:5.7'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: go1
            MYSQL_PASSWORD: go1
        volumes:
            - './.data/mysql:/var/lib/mysql'
        ports:
            - '3306:3306'
    neo4j:
        image: neo4j
        environment:
            - NEO4J_AUTH=none
        volumes:
          - './.data/neo4j:/data'
        ports:
            - '7474:7474'
            - '7687:7687'
    queue:
        image: 'rabbitmq:3.6-management'
        environment:
            - RABBITMQ_DEFAULT_USER=go1
            - RABBITMQ_DEFAULT_PASS=go1
        ports:
          - '15672:15672'
    memcached:
        image: 'memcached:1.4-alpine'
    es:
        image: "go1com/ci-elasticsearch"
        volumes:
            - './.data/elasticsearch:/usr/share/elasticsearch/data'
        ports:
            - '9200:9200'
    consumer:
        build: ./.data/consumer
        command:
            - /app/app
        links:
            - queue
            - web
        environment:
            - QUEUE_URL=amqp://go1:go1@queue:5672/
            - SERVICE_URL_PATTERN=http://web/GO1/SERVICE/consume
            - CONSUMER_algolia=lo.create,lo.update,lo.delete,vote.#
            - CONSUMER_api=do.public-api.webhook-request,lo.#,enrolment.#,user.#,ro.create,ro.delete
            - CONSUMER_assessor=lo.delete,enrolment.delete,enrolment.create
            - CONSUMER_cloudinary=lo.delete,user.delete,portal.delete
            - CONSUMER_enrolment=enrolment.update
            - CONSUMER_graphin=portal.#,user.#,lo.#,enrolment.#,tag.#,vote.#,group.#,ro.#,note.#
            - CONSUMER_low=group.#
            - CONSUMER_rules=portal.#,user.#,lo.#,enrolment.#,system.#
            - CONSUMER_stash=stash.#
            - CONSUMER_notify=enrolment.#,user.#,note.#,ro.#
            - CONSUMER_lazy=do.#
            - CONSUMER_oembed=lo.update
            # - CONSUMER_eck=enrolment.delete,lo.delete,portal.delete,user.delete
            # - CONSUMER_index=portal.#,portal-config.#,user.#,lo.#,enrolment.#,ro.#
            # - CONSUMER_natero=portal.create,portal.update,contract.create,contract.update
        depends_on:
            - queue
        command: ["/scripts/wait-for-it.sh", "queue:5672", "-t", "0", "--", "/app/app"]
        volumes:
            - './infrastructure/wait-for-it:/scripts'
    worker:
        build: ./.data/worker
        command:
            - /app/app
        links:
            - queue
            - web
        environment:
            - QUEUE_URL=amqp://go1:go1@queue:5672/
            - SERVICE_URL_PATTERN=http://web/GO1/SERVICE/consume
        depends_on:
            - queue
        command: ["/scripts/wait-for-it.sh", "queue:5672", "-t", "0", "--", "/app/app"]
        volumes:
            - './infrastructure/wait-for-it:/scripts'
    ui:
        image: 'registry.code.go1.com.au/apiom/apiom-ui:master'
        command: ["ping", "127.0.0.1", "-q"]
    web:
        build: ./.data/debug
        links:
            - memcached
            - neo4j
            - mysql
            - queue
            - es
        ports:
            - '80:80'
        volumes:
            - './php/:/app/'
            - './php/vendor:/vendor/'
            - './.data/drupal/:/drupal/'
            - './.data/nginx/sites-available/:/etc/nginx/sites-available/'
            - './.data/nginx/autoload/:/autoload/'
            - './.data/cli/:/cli/'
            - './scripts/:/scripts/'
            - './.data/resources/docker/:/app/resources/docker/'
        volumes_from:
              - ui
        environment:
            - _DOCKER_RDS_DB_NAME=go1_dev
            - _DOCKER_RDS_HOSTNAME=mysql
            - _DOCKER_RDS_PASSWORD=root
            - _DOCKER_RDS_USERNAME=root
            - _DOCKER_GO1_DB_NAME=go1_dev
            - _DOCKER_GO1_HOSTNAME=mysql
            - _DOCKER_GO1_PASSWORD=root
            - _DOCKER_GO1_USERNAME=root
            - _DOCKER_CACHE_BACKEND=memcached
            - _DOCKER_CACHE_HOST=memcached
            - _DOCKER_CACHE_PORT=11211
            - _DOCKER_QUEUE_HOST=queue
            - MONOLITH=1
            - ENV=dev
            - SERVICE_URL_PATTERN=http://web/GO1/SERVICE
            - ES_URL=http://es:9200
